version: '3'
services:

  stack_php8:
    container_name: stackPhp8
    build:
      context: .
      dockerfile: php8.Dockerfile
    volumes:
      - "../:/var/www/app"

  stack_php7:
    container_name: stackPhp7
    build:
      context: .
      dockerfile: php7.Dockerfile
    volumes:
      - "..:/var/www/app"

