name: pr-unit-tests
on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Environment
        run: docker compose -f .docker/docker-compose.yml up -d

      - name: Stack PHP7 | Installing dependencies
        run: docker exec stackPhp7 composer install --optimize-autoloader

      - name: Stack PHP7 | Executando testes únitarios
        run: docker exec stackPhp7 ./vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Removing vendor folder and composer.lock file
        run: rm -rf vendor composer.lock

      - name: Stack PHP8 | Installing dependencies
        run: docker exec stackPhp8 composer install --optimize-autoloader

      - name: Stack PHP8 | Executando testes únitarios
        run: docker exec stackPhp8 ./vendor/bin/phpunit --coverage-clover=coverage.xml
